version: "3"

services:
  main:
    build: .
    volumes:
      - .:/app
    ports: 
      - 80:80
  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  s3:
    image: minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - ./s3/data/:/data
    ports:
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: access
      MINIO_SECRET_KEY: secret 
    labels:
      - traefik.http.routes.s3.rule=Host(`s3.localhost`)

  postgres:
    image: postgres:12
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: classroom
    volumes:
      - classroom-postgres:/var/lib/postgresql/data


volumes:
  classroom-postgres:
    external: false